// LOCALHOST
GET http://localhost/3000 HTTP/1.1
### 
GET http://localhost:8080/contacts 
### 
GET http://localhost:8080/contacts/644a923e4250c726a4d072fd
### 
GET http://localhost:8080/contacts/644a926e4250c726a4d072fe
### 
GET http://localhost:8080/contacts/644ab1114250c726a4d07309


//PRODUCTION Deploy
### 
GET http://cse341-project-1.onrender.com/contacts HTTP/1.1